name: git push into private repo to deploy to vercel

on:
  push:
    branches:
      - feature/cicd

jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex
    steps:
      - uses: actions/checkout@v2
      - name: Install mustache (to update the date)
        run: apk add ruby && gem install mustache
      - name: creates output
        run: sh ./build.sh
      - name: Pushes to another repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.STAY_TUNE_DEPLOY }}
        with:
          source-directory: "output"
          destination-github-username: "holim0"
          destination-repository-name: "stay-tune-frontend-Deploy"
          user-email: ${{ secrets.DEPLOY_EMAIL }}
          commit-message: ${{ github.event.commits[0].message }}
          target-branch: main
      - name: Test get variable exported by push-to-another-repository
        run: echo $DESTINATION_CLONED_DIRECTORY
